# pr-automation.yml（提交到web-application仓库的main分支下的对应路径）
name: PR Automation Checks（代码质量/测试/安全/构建）
on:
  pull_request:
    types: [opened, synchronize, reopened]  # 匹配脚本必需触发事件
jobs:
  # 1. 代码质量检查（对应脚本required_jobs：code-quality）
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint  # 执行ESLint检查，故意错误会失败

  # 2. 测试执行（对应脚本required_jobs：testing-suite）
  testing-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test  # 执行Jest测试，故意错误会失败

  # 3. 安全扫描（对应脚本required_jobs：security-scan）
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run secret detection
        uses: gitguardian/gh-action@v1.15.0
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_KEY }}  # 需在仓库配置该secret，测试时可暂用占位符

  # 4. 构建验证（对应脚本required_jobs：build-validation）
  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build  # 执行Webpack构建，依赖缺失会失败

  # 5. 自动化评论（生成4类报告，对应脚本PR_COMMENT配置）
  auto-comment:
    needs: [code-quality, testing-suite, security-scan, build-validation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate reports and comment
        uses: actions/github-script@v7
        with:
          script: |
            // 模拟生成4类报告（实际项目需根据真实结果生成）
            const reports = `
            ## Code Quality Report
            Code Quality Check Results: ESLint passed. Total Issues: 0. Pass Rate: 100%
            
            ## Test Coverage Report
            Test Coverage Results: Jest passed. Coverage: 85%+
            
            ## Security Scan Report
            Security Scan Results: Secret Detection passed. No Secrets Found
            
            ## Build Validation Report
            Build Check Results: Webpack passed. Build Successful
            `;
            // 向PR添加评论（github-actions[bot]账号）
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: reports
            });
